In [1]:
import pandas as pd
pd.__version__

'1.2.4'

In [2]:
import matplotlib.pyplot as plt

In [3]:
# Adjust plot size
#options(repr.plot.width=16, repr.plot.height=6)

# For some reason, if this is in the same cell as the import command, it doesn't work.
plt.rcParams["figure.figsize"] = [18.0,8.0]

# Read Read Lengths

In [4]:
df=pd.read_csv("data/read_lengths.csv",header=None,
 names=['sequencing','length'])
df.head()

             sequencing  length
0  02-2483-01A-01D-1494     101
1  02-2483-10A-01D-1494     101
2  02-2485-01A-01D-1494     101
3  02-2485-10A-01D-1494     101
4  06-0125-01A-01D-1490     101

In [5]:
df['sample']=df['sequencing'].str[0:11]
df['subject']=df['sequencing'].str[0:7]

In [6]:
df.head()

             sequencing  length       sample  subject
0  02-2483-01A-01D-1494     101  02-2483-01A  02-2483
1  02-2483-10A-01D-1494     101  02-2483-10A  02-2483
2  02-2485-01A-01D-1494     101  02-2485-01A  02-2485
3  02-2485-10A-01D-1494     101  02-2485-10A  02-2485
4  06-0125-01A-01D-1490     101  06-0125-01A  06-0125

# Read counts

In [7]:
# header uses subject and not sample
#rc=pd.read_csv("data/TCGA_raw_counts.csv",header=0, names=['sample','count'])
rc=pd.read_csv("data/TCGA_raw_counts.csv")
rc.rename(columns={"subject": "sample"},inplace=True)
#rc['subject']=rc['sample'].astype(str).str[0:7]
rc.head()

        sample  raw pair count
0  02-2483-01A       566024474
1  02-2483-10A       579304076
2  02-2485-01A       575060540
3  02-2485-10A       478851061
4  06-0125-01A      1066268796

In [8]:
df=df.merge(rc,on='sample')
del rc
df.head()

             sequencing  length       sample  subject  raw pair count
0  02-2483-01A-01D-1494     101  02-2483-01A  02-2483       566024474
1  02-2483-10A-01D-1494     101  02-2483-10A  02-2483       579304076
2  02-2485-01A-01D-1494     101  02-2485-01A  02-2485       575060540
3  02-2485-10A-01D-1494     101  02-2485-10A  02-2485       478851061
4  06-0125-01A-01D-1490     101  06-0125-01A  06-0125      1066268796

# Read Metadata 1

In [9]:
mt=pd.read_csv("data/metadata.cart.TCGA.GBM-LGG.WGS.bam.2020-07-17.csv",header=None,
 names=['submitter','days_to_death','gender','disease_type','center_name'])

In [10]:
mt.shape

(127, 5)

In [11]:
mt.rename(columns={"submitter": "subject"},inplace=True)

In [12]:
mt.head()

,subject,days_to_death,gender,disease_type,center_name
0,02-2483,NaN,male,Glioblastoma Multiforme,Broad Institute of MIT and Harvard
1,02-2485,NaN,male,Glioblastoma Multiforme,Broad Institute of MIT and Harvard
2,06-0125,1448.0,female,Glioblastoma Multiforme,Broad Institute of MIT and Harvard
3,06-0152,375.0,male,Glioblastoma Multiforme,Broad Institute of MIT and Harvard
4,06-0157,97.0,female,Glioblastoma Multiforme,Broad Institute of MIT and Harvard

In [13]:
list(mt)

['subject', 'days_to_death', 'gender', 'disease_type', 'center_name']

In [14]:
df=df.merge(mt,on='subject')
del mt
df.head()

,sequencing,length,sample,subject,raw pair count,days_to_death,gender,disease_type,center_name
0,02-2483-01A-01D-1494,101,02-2483-01A,02-2483,566024474,NaN,male,Glioblastoma Multiforme,Broad Institute of MIT and Harvard
1,02-2483-10A-01D-1494,101,02-2483-10A,02-2483,579304076,NaN,male,Glioblastoma Multiforme,Broad Institute of MIT and Harvard
2,02-2485-01A-01D-1494,101,02-2485-01A,02-2485,575060540,NaN,male,Glioblastoma Multiforme,Broad Institute of MIT and Harvard
3,02-2485-10A-01D-1494,101,02-2485-10A,02-2485,478851061,NaN,male,Glioblastoma Multiforme,Broad Institute of MIT and Harvard
4,06-0125-01A-01D-1490,101,06-0125-01A,06-0125,1066268796,1448.0,female,Glioblastoma Multiforme,Broad Institute of MIT and Harvard

# Read Metadata 2

In [15]:
mt2=pd.read_csv("data/TCGA.Glioma.metadata.tsv",sep="\t")

In [16]:
mt2.shape

(1114, 18)

In [17]:
mt2.head()

,case_submitter_id,project_id,primary_diagnosis,race,ethnicity,gender,RE_names,IDH,x1p19q,TERT,IDH_1p19q_status,WHO_groups,Triple_group,Tissue_sample_location,MGMT,Age,Survival_months,Vital_status
0,TCGA-02-0001,TCGA-GBM,Glioblastoma,white,not hispanic or latino,female,NaN,WT,non-codel,NaN,IDH-WT:1p19q-non-codel,glioblastoma:IDH-WT:1p19q-non-codel,IDH-WT:1p19q-non-codel:TERT-NA,MD Anderson Cancer Center,Unmethylated,44.0,11.762054,1.0
1,TCGA-02-0003,TCGA-GBM,Glioblastoma,white,not hispanic or latino,male,NaN,WT,non-codel,NaN,IDH-WT:1p19q-non-codel,glioblastoma:IDH-WT:1p19q-non-codel,IDH-WT:1p19q-non-codel:TERT-NA,MD Anderson Cancer Center,Unmethylated,50.0,4.731106,1.0
2,TCGA-02-0004,TCGA-GBM,Glioblastoma,white,not hispanic or latino,male,NaN,WT,NaN,NaN,IDH-WT:1p19q-NA,NaN,IDH-WT:1p19q-NA:TERT-NA,MD Anderson Cancer Center,NaN,59.0,11.334941,1.0
3,TCGA-02-0006,TCGA-GBM,Glioblastoma,white,not hispanic or latino,female,NaN,WT,non-codel,NaN,IDH-WT:1p19q-non-codel,glioblastoma:IDH-WT:1p19q-non-codel,IDH-WT:1p19q-non-codel:TERT-NA,MD Anderson Cancer Center,Unmethylated,56.0,18.333034,1.0
4,TCGA-02-0007,TCGA-GBM,Glioblastoma,white,not hispanic or latino,female,NaN,WT,non-codel,NaN,IDH-WT:1p19q-non-codel,glioblastoma:IDH-WT:1p19q-non-codel,IDH-WT:1p19q-non-codel:TERT-NA,MD Anderson Cancer Center,Unmethylated,40.0,23.162705,1.0

In [18]:
mt2['subject']=mt2['case_submitter_id'].astype(str).str[5:12]

In [19]:
mt2[['subject','case_submitter_id']].head()

   subject case_submitter_id
0  02-0001      TCGA-02-0001
1  02-0003      TCGA-02-0003
2  02-0004      TCGA-02-0004
3  02-0006      TCGA-02-0006
4  02-0007      TCGA-02-0007

In [20]:
list(mt2)

['case_submitter_id',
 'project_id',
 'primary_diagnosis',
 'race',
 'ethnicity',
 'gender',
 'RE_names',
 'IDH',
 'x1p19q',
 'TERT',
 'IDH_1p19q_status',
 'WHO_groups',
 'Triple_group',
 'Tissue_sample_location',
 'MGMT',
 'Age',
 'Survival_months',
 'Vital_status',
 'subject']

# Merge Metadata

In [21]:
df=df.merge(mt2,on='subject',suffixes=["_mt2","_mt"]) #,how='inner')
del mt2
df.head()

,sequencing,length,sample,subject,raw pair count,days_to_death,gender_mt2,disease_type,center_name,case_submitter_id,...,x1p19q,TERT,IDH_1p19q_status,WHO_groups,Triple_group,Tissue_sample_location,MGMT,Age,Survival_months,Vital_status
0,02-2483-01A-01D-1494,101,02-2483-01A,02-2483,566024474,NaN,male,Glioblastoma Multiforme,Broad Institute of MIT and Harvard,TCGA-02-2483,...,non-codel,WT,IDH-Mutant:1p19q-non-codel,glioblastoma:IDH-Mutant:1p19q-non-codel,IDH-Mutant:1p19q-non-codel:TERT-WT,MD Anderson Cancer Center,Methylated,43.0,15.310383,0.0
1,02-2483-10A-01D-1494,101,02-2483-10A,02-2483,579304076,NaN,male,Glioblastoma Multiforme,Broad Institute of MIT and Harvard,TCGA-02-2483,...,non-codel,WT,IDH-Mutant:1p19q-non-codel,glioblastoma:IDH-Mutant:1p19q-non-codel,IDH-Mutant:1p19q-non-codel:TERT-WT,MD Anderson Cancer Center,Methylated,43.0,15.310383,0.0
2,02-2485-01A-01D-1494,101,02-2485-01A,02-2485,575060540,NaN,male,Glioblastoma Multiforme,Broad Institute of MIT and Harvard,TCGA-02-2485,...,non-codel,Mutant,IDH-WT:1p19q-non-codel,glioblastoma:IDH-WT:1p19q-non-codel,IDH-WT:1p19q-non-codel:TERT-Mutant,MD Anderson Cancer Center,Unmethylated,53.0,15.441803,0.0
3,02-2485-10A-01D-1494,101,02-2485-10A,02-2485,478851061,NaN,male,Glioblastoma Multiforme,Broad Institute of MIT and Harvard,TCGA-02-2485,...,non-codel,Mutant,IDH-WT:1p19q-non-codel,glioblastoma:IDH-WT:1p19q-non-codel,IDH-WT:1p19q-non-codel:TERT-Mutant,MD Anderson Cancer Center,Unmethylated,53.0,15.441803,0.0
4,06-0125-01A-01D-1490,101,06-0125-01A,06-0125,1066268796,1448.0,female,Glioblastoma Multiforme,Broad Institute of MIT and Harvard,TCGA-06-0125,...,non-codel,Mutant,IDH-WT:1p19q-non-codel,glioblastoma:IDH-WT:1p19q-non-codel,IDH-WT:1p19q-non-codel:TERT-Mutant,Henry Ford Hospital,Methylated,63.0,47.573895,1.0

In [22]:
list(df)

['sequencing',
 'length',
 'sample',
 'subject',
 'raw pair count',
 'days_to_death',
 'gender_mt2',
 'disease_type',
 'center_name',
 'case_submitter_id',
 'project_id',
 'primary_diagnosis',
 'race',
 'ethnicity',
 'gender_mt',
 'RE_names',
 'IDH',
 'x1p19q',
 'TERT',
 'IDH_1p19q_status',
 'WHO_groups',
 'Triple_group',
 'Tissue_sample_location',
 'MGMT',
 'Age',
 'Survival_months',
 'Vital_status']

In [23]:
df.shape

(287, 27)

In [24]:
df[df['subject']=='CS-6186']

,sequencing,length,sample,subject,raw pair count,days_to_death,gender_mt2,disease_type,center_name,case_submitter_id,...,x1p19q,TERT,IDH_1p19q_status,WHO_groups,Triple_group,Tissue_sample_location,MGMT,Age,Survival_months,Vital_status
89,CS-6186-01A-12D-2022,51,CS-6186-01A,CS-6186,903668222,538.0,male,Brain Lower Grade Glioma,Broad Institute of MIT and Harvard,TCGA-CS-6186,...,non-codel,Mutant,IDH-WT:1p19q-non-codel,oligoastrocytoma:IDH-WT:1p19q-non-codel,IDH-WT:1p19q-non-codel:TERT-Mutant,Thomas Jefferson University,Unmethylated,58.0,17.675936,1.0
90,CS-6186-01A-12D-2022,51,CS-6186-01A,CS-6186,903668222,538.0,male,Brain Lower Grade Glioma,Harvard Medical School,TCGA-CS-6186,...,non-codel,Mutant,IDH-WT:1p19q-non-codel,oligoastrocytoma:IDH-WT:1p19q-non-codel,IDH-WT:1p19q-non-codel:TERT-Mutant,Thomas Jefferson University,Unmethylated,58.0,17.675936,1.0
91,CS-6186-01A-12D-A461,151,CS-6186-01A,CS-6186,903668222,538.0,male,Brain Lower Grade Glioma,Broad Institute of MIT and Harvard,TCGA-CS-6186,...,non-codel,Mutant,IDH-WT:1p19q-non-codel,oligoastrocytoma:IDH-WT:1p19q-non-codel,IDH-WT:1p19q-non-codel:TERT-Mutant,Thomas Jefferson University,Unmethylated,58.0,17.675936,1.0
92,CS-6186-01A-12D-A461,151,CS-6186-01A,CS-6186,903668222,538.0,male,Brain Lower Grade Glioma,Harvard Medical School,TCGA-CS-6186,...,non-codel,Mutant,IDH-WT:1p19q-non-codel,oligoastrocytoma:IDH-WT:1p19q-non-codel,IDH-WT:1p19q-non-codel:TERT-Mutant,Thomas Jefferson University,Unmethylated,58.0,17.675936,1.0
93,CS-6186-10A-01D-2022,51,CS-6186-10A,CS-6186,519547041,538.0,male,Brain Lower Grade Glioma,Broad Institute of MIT and Harvard,TCGA-CS-6186,...,non-codel,Mutant,IDH-WT:1p19q-non-codel,oligoastrocytoma:IDH-WT:1p19q-non-codel,IDH-WT:1p19q-non-codel:TERT-Mutant,Thomas Jefferson University,Unmethylated,58.0,17.675936,1.0
94,CS-6186-10A-01D-2022,51,CS-6186-10A,CS-6186,519547041,538.0,male,Brain Lower Grade Glioma,Harvard Medical School,TCGA-CS-6186,...,non-codel,Mutant,IDH-WT:1p19q-non-codel,oligoastrocytoma:IDH-WT:1p19q-non-codel,IDH-WT:1p19q-non-codel:TERT-Mutant,Thomas Jefferson University,Unmethylated,58.0,17.675936,1.0
95,CS-6186-10A-01D-2024,151,CS-6186-10A,CS-6186,519547041,538.0,male,Brain Lower Grade Glioma,Broad Institute of MIT and Harvard,TCGA-CS-6186,...,non-codel,Mutant,IDH-WT:1p19q-non-codel,oligoastrocytoma:IDH-WT:1p19q-non-codel,IDH-WT:1p19q-non-codel:TERT-Mutant,Thomas Jefferson University,Unmethylated,58.0,17.675936,1.0
96,CS-6186-10A-01D-2024,151,CS-6186-10A,CS-6186,519547041,538.0,male,Brain Lower Grade Glioma,Harvard Medical School,TCGA-CS-6186,...,non-codel,Mutant,IDH-WT:1p19q-non-codel,oligoastrocytoma:IDH-WT:1p19q-non-codel,IDH-WT:1p19q-non-codel:TERT-Mutant,Thomas Jefferson University,Unmethylated,58.0,17.675936,1.0

In [25]:
df[df['subject']=='DU-5872']

,sequencing,length,sample,subject,raw pair count,days_to_death,gender_mt2,disease_type,center_name,case_submitter_id,...,x1p19q,TERT,IDH_1p19q_status,WHO_groups,Triple_group,Tissue_sample_location,MGMT,Age,Survival_months,Vital_status
131,DU-5872-01A-11D-1703,51,DU-5872-01A,DU-5872,925093747,NaN,female,Brain Lower Grade Glioma,Broad Institute of MIT and Harvard,TCGA-DU-5872,...,non-codel,WT,IDH-Mutant:1p19q-non-codel,oligoastrocytoma:IDH-Mutant:1p19q-non-codel,IDH-Mutant:1p19q-non-codel:TERT-WT,Henry Ford Hospital,Methylated,43.0,17.478807,0.0
132,DU-5872-01A-11D-1703,51,DU-5872-01A,DU-5872,925093747,NaN,female,Brain Lower Grade Glioma,Harvard Medical School,TCGA-DU-5872,...,non-codel,WT,IDH-Mutant:1p19q-non-codel,oligoastrocytoma:IDH-Mutant:1p19q-non-codel,IDH-Mutant:1p19q-non-codel:TERT-WT,Henry Ford Hospital,Methylated,43.0,17.478807,0.0
133,DU-5872-01A-11D-A465,151,DU-5872-01A,DU-5872,925093747,NaN,female,Brain Lower Grade Glioma,Broad Institute of MIT and Harvard,TCGA-DU-5872,...,non-codel,WT,IDH-Mutant:1p19q-non-codel,oligoastrocytoma:IDH-Mutant:1p19q-non-codel,IDH-Mutant:1p19q-non-codel:TERT-WT,Henry Ford Hospital,Methylated,43.0,17.478807,0.0
134,DU-5872-01A-11D-A465,151,DU-5872-01A,DU-5872,925093747,NaN,female,Brain Lower Grade Glioma,Harvard Medical School,TCGA-DU-5872,...,non-codel,WT,IDH-Mutant:1p19q-non-codel,oligoastrocytoma:IDH-Mutant:1p19q-non-codel,IDH-Mutant:1p19q-non-codel:TERT-WT,Henry Ford Hospital,Methylated,43.0,17.478807,0.0
135,DU-5872-02A-21D-A36O,151,DU-5872-02A,DU-5872,759081398,NaN,female,Brain Lower Grade Glioma,Broad Institute of MIT and Harvard,TCGA-DU-5872,...,non-codel,WT,IDH-Mutant:1p19q-non-codel,oligoastrocytoma:IDH-Mutant:1p19q-non-codel,IDH-Mutant:1p19q-non-codel:TERT-WT,Henry Ford Hospital,Methylated,43.0,17.478807,0.0
136,DU-5872-02A-21D-A36O,151,DU-5872-02A,DU-5872,759081398,NaN,female,Brain Lower Grade Glioma,Harvard Medical School,TCGA-DU-5872,...,non-codel,WT,IDH-Mutant:1p19q-non-codel,oligoastrocytoma:IDH-Mutant:1p19q-non-codel,IDH-Mutant:1p19q-non-codel:TERT-WT,Henry Ford Hospital,Methylated,43.0,17.478807,0.0
137,DU-5872-10A-01D-1703,51,DU-5872-10A,DU-5872,527966091,NaN,female,Brain Lower Grade Glioma,Broad Institute of MIT and Harvard,TCGA-DU-5872,...,non-codel,WT,IDH-Mutant:1p19q-non-codel,oligoastrocytoma:IDH-Mutant:1p19q-non-codel,IDH-Mutant:1p19q-non-codel:TERT-WT,Henry Ford Hospital,Methylated,43.0,17.478807,0.0
138,DU-5872-10A-01D-1703,51,DU-5872-10A,DU-5872,527966091,NaN,female,Brain Lower Grade Glioma,Harvard Medical School,TCGA-DU-5872,...,non-codel,WT,IDH-Mutant:1p19q-non-codel,oligoastrocytoma:IDH-Mutant:1p19q-non-codel,IDH-Mutant:1p19q-non-codel:TERT-WT,Henry Ford Hospital,Methylated,43.0,17.478807,0.0
139,DU-5872-10A-01D-A465,151,DU-5872-10A,DU-5872,527966091,NaN,female,Brain Lower Grade Glioma,Broad Institute of MIT and Harvard,TCGA-DU-5872,...,non-codel,WT,IDH-Mutant:1p19q-non-codel,oligoastrocytoma:IDH-Mutant:1p19q-non-codel,IDH-Mutant:1p19q-non-codel:TERT-WT,Henry Ford Hospital,Methylated,43.0,17.478807,0.0
140,DU-5872-10A-01D-A465,151,DU-5872-10A,DU-5872,527966091,NaN,female,Brain Lower Grade Glioma,Harvard Medical School,TCGA-DU-5872,...,non-codel,WT,IDH-Mutant:1p19q-non-codel,oligoastrocytoma:IDH-Mutant:1p19q-non-codel,IDH-Mutant:1p19q-non-codel:TERT-WT,Henry Ford Hospital,Methylated,43.0,17.478807,0.0

Looks like there are a couple duplicate merges?

* CS-6186
* DU-5872

1 of each gets trimmed away later by the center selection.

In [26]:
df[['subject','sample','sequencing','length','raw pair count','disease_type']]

,subject,sample,sequencing,length,raw pair count,disease_type
0,02-2483,02-2483-01A,02-2483-01A-01D-1494,101,566024474,Glioblastoma Multiforme
1,02-2483,02-2483-10A,02-2483-10A-01D-1494,101,579304076,Glioblastoma Multiforme
2,02-2485,02-2485-01A,02-2485-01A-01D-1494,101,575060540,Glioblastoma Multiforme
3,02-2485,02-2485-10A,02-2485-10A-01D-1494,101,478851061,Glioblastoma Multiforme
4,06-0125,06-0125-01A,06-0125-01A-01D-1490,101,1066268796,Glioblastoma Multiforme
...,...,...,...,...,...,...
282,TQ-A7RV,TQ-A7RV-02A,TQ-A7RV-02A-11D-A36O,151,697454066,Brain Lower Grade Glioma
283,TQ-A7RV,TQ-A7RV-10A,TQ-A7RV-10A-01D-A34A,151,362586651,Brain Lower Grade Glioma
284,TQ-A8XE,TQ-A8XE-01A,TQ-A8XE-01A-11D-A36O,151,724443745,Brain Lower Grade Glioma
285,TQ-A8XE,TQ-A8XE-02A,TQ-A8XE-02A-11D-A36O,151,628610301,Brain Lower Grade Glioma
286,TQ-A8XE,TQ-A8XE-10A,TQ-A8XE-10A-01D-A367,151,371365326,Brain Lower Grade Glioma